name: Rockflower
favicon: null
layout_spectrum: 0.5897626744117588
typography_spectrum: 0.31793663930147886
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4785335483029485
  lightness: 0.9993095705285668
  saturation: 0.47630783054046333
  rhythmicContrast: 0.019823606126010418
purpose: []
