name: Rockflower
favicon: null
layout_spectrum: 0.5897626744117588
typography_spectrum: 0.31793663930147886
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3c0a70'
    - '#464028'
    - '#9a988d'
    - '#dcd9cf'
  brandStrength: 0.5
  lightness: 0.9993095705285668
  saturation: 0.47630783054046333
  rhythmicContrast: 0
purpose: []
